Repository containers/podman-py, pull requests merged in 2021-09, with the labels that each got.

#131 Update tests re: changes in containers.logs()
  podman/tests/integration/test_containers.py
Labels: bug, approved

#132 Revert pyproject.toml requires changes
  .cirrus.yml
  contrib/cirrus/build_podman.sh
  contrib/cirrus/enable_podman.sh
  contrib/cirrus/enable_ssh.sh
  contrib/cirrus/latest_podman.sh
  contrib/cirrus/test.sh
  podman.svg
  podman/tests/integration/test_containers.py
  pyproject.toml
Labels: bug, approved, lgtm

#133 Remove disused bors cruft
  .cirrus.yml
  bors.toml
Labels: approved, lgtm

#134 Cleanup code and CI
  podman/__init__.py
  podman/api/__init__.py
  podman/api/client.py
  podman/api/ssh.py
  podman/api/typing_extensions.py
  podman/tests/integration/base.py
  podman/tests/integration/test_adapters.py
  podman/tests/integration/test_manifests.py
  podman/tests/integration/test_pods.py
  podman/tests/integration/test_system.py
  podman/tests/integration/utils.py
  podman/tests/unit/test_api_utils.py
  podman/tests/unit/test_build.py
  podman/tests/unit/test_container.py
  podman/tests/unit/test_containersmanager.py
  podman/tests/unit/test_image.py
  podman/tests/unit/test_imagesmanager.py
  podman/tests/unit/test_pod.py
  podman/tests/unit/test_podsmanager.py
  podman/tests/unit/test_registrydata.py
  podman/tests/unit/test_system.py
  pyproject.toml
Labels: approved

#135 Bump version and publish release
  podman/tests/__init__.py
  podman/version.py
Labels: approved

#137 Assert Python version >= 3.6
  podman/__init__.py
Labels: enhancement, approved

#136 Update Sphinx configuration
  .readthedocs.yaml
  docs/source/conf.py
Labels: documentation, approved
