Repository containers/podman-py, pull requests merged in 2022-10, with the labels that each got.

#202 Adding support of passing empty strings
  podman/api/http_utils.py
  podman/tests/unit/test_api_utils.py
Labels: approved, lgtm

#211 backports for v4.0.0
  .cirrus.yml
  podman/domain/containers_create.py
  podman/tests/integration/test_container_create.py
Labels: lgtm

#215 add support for healthcheck on failure actions for 4.2.0
  .cirrus.yml
  podman/domain/containers_create.py
  podman/tests/integration/test_container_create.py
Labels: approved, lgtm

#216 Bump version to 4.3.0
  Makefile
  podman/tests/__init__.py
  podman/version.py
Labels: approved, lgtm

#217 bump to v4.2.1
  Makefile
  podman/tests/__init__.py
  podman/version.py
Labels: approved, lgtm

#210 update urllib to 1.26.5 for a CVE found in previous versions
  pyproject.toml
  requirements.txt
  setup.cfg
Labels: approved, lgtm

#219 Correct path for rtd conf.py
  .readthedocs.yaml
Labels: approved

#220 enable readthedoc builds
  .readthedocs.yaml
  docs/source/index.rst
Labels: approved
