Repository containers/podman-py, pull requests merged in 2022-03, with the labels that each got.

#163 Add missing to_bytes for memswap_limit
  podman/domain/containers_create.py
  podman/tests/integration/test_container_create.py
Labels: approved, lgtm

#162 Fix stream option for container logs
  podman/domain/containers.py
Labels: approved, lgtm

#164 #121 Set X-Registry-Auth header on image push
  podman/api/http_utils.py
  podman/domain/images_manager.py
Labels: approved

#169 Fix container commit()
  podman/domain/containers.py
  podman/tests/integration/test_containers.py
  podman/tests/unit/test_container.py
Labels: bug, approved
