Repository containers/podman-py, pull requests merged in 2022-01, with the labels that each got.

#158 Cirrus: Update Fedora + Ubuntu CI VMs
  .cirrus.yml
  .github/workflows/pr.yml
Labels: lgtm

#149 Fixup lint items
  .pylintrc
  podman/api/client.py
  podman/api/http_utils.py
  podman/api/parse_utils.py
  podman/api/ssh.py
  podman/api/tar_utils.py
  podman/api/typing_extensions.py
  podman/api/uds.py
  podman/api_connection.py
  podman/client.py
  podman/containers/__init__.py
  podman/domain/config.py
  podman/domain/containers.py
  podman/domain/containers_create.py
  podman/domain/containers_manager.py
  podman/domain/images.py
  podman/domain/images_build.py
  podman/domain/images_manager.py
  podman/domain/ipam.py
  podman/domain/manager.py
  podman/domain/manifests.py
  podman/domain/networks.py
  podman/domain/networks_manager.py
  podman/domain/pods_manager.py
  podman/domain/secrets.py
  podman/domain/volumes.py
  podman/images/__init__.py
  podman/manifests/__init__.py
  podman/networks/__init__.py
  podman/pods/__init__.py
  podman/system/__init__.py
  podman/tests/integration/base.py
  podman/tests/integration/test_container_create.py
  podman/tests/integration/test_containers.py
  podman/tests/integration/utils.py
  podman/tests/unit/test_build.py
  podman/tests/unit/test_config.py
  podman/tests/unit/test_container.py
  podman/tests/unit/test_containersmanager.py
  podman/tests/unit/test_imagesmanager.py
  podman/tests/unit/test_podmanclient.py
Labels: approved

#159 [Technical Debt] Remove ApiConnection support
  Makefile
  podman/__init__.py
  podman/api/client.py
  podman/api/typing_extensions.py
  podman/api_connection.py
  podman/containers/__init__.py
  podman/domain/containers_create.py
  podman/domain/pods_manager.py
  podman/images/__init__.py
  podman/manifests/__init__.py
  podman/networks/__init__.py
  podman/pods/__init__.py
  podman/system/__init__.py
  podman/tests/unit/containers/__init__.py
  podman/tests/unit/containers/test_containers.py
  podman/tests/unit/images/__init__.py
  podman/tests/unit/images/test_images.py
  podman/tests/unit/manifests/__init__.py
  podman/tests/unit/manifests/test_manifests.py
  podman/tests/unit/networks/__init__.py
  podman/tests/unit/networks/test_networks.py
  podman/tests/unit/pods/__init__.py
  podman/tests/unit/pods/test_pods.py
  podman/tests/unit/system/__init__.py
  podman/tests/unit/system/test_system.py
  podman/tests/unit/test_api_connection.py
  podman/tests/unit/test_config.py
  podman/tests/unit/test_containersmanager.py
  podman/tests/unit/test_parse_utils.py
Labels: approved, lgtm
